server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/kokan_user
    username: root
    password: SaiMysql$2003!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: mySuperSecretKeyForJWT1234567890! 
  expiration: 3600000 
